apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical-cluster-store
spec:
  provider:
    infisical:
      hostAPI: http://infisical-app-svc.infisical.svc.cluster.local:8080
      auth:
        tokenAuthCredentials:
          accessToken:
            name: infisical-service-token
            namespace: external-secrets
            key: accessToken
      secretsScope:
        # The project and environment slugs can be found in the Project Settings > General section of the Infisical dashboard
        projectSlug: astra-yrel
        # The environment slug is typically "dev", "staging", or "prod", depending on how you have set up your environments in Infisical
        environmentSlug: prod
