services:
  crafty:
    container_name: crafty
    image: registry.gitlab.com/crafty-controller/crafty-4:4.10.4
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Paris
    volumes:
      - /mnt/data/docker-volumes/crafty/backups:/crafty/backups
      - /mnt/data/docker-volumes/crafty/logs:/crafty/logs
      - /mnt/data/docker-volumes/crafty/servers:/crafty/servers
      - /mnt/data/docker-volumes/crafty/config:/crafty/app/config
      - /mnt/data/docker-volumes/crafty/import:/crafty/import

  watcher:
    image: ghcr.io/soveticka/crafty-server-watcher:latest
    container_name: crafty_watcher
    restart: always
    network_mode: host
    volumes:
      - /opt/docker-data/crafty/watcher/config.yaml:/config/config.yaml:ro
    environment:
      - CRAFTY_API_TOKEN=${CRAFTY_API_TOKEN}
    depends_on:
      - crafty
