namespace: web

image:
  repository: ghcr.io/enoal-fauchille-bolle/cv
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80
  targetPort: 50021

ingress:
  hosts:
    - cv-astra.enoal.fr

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi

imagePullSecrets:
  - name: regcred-cv
