#!/bin/bash
# Copies the Proxmox VE and Proxmox Backup Server configuration of Astra to Pulsar, where
# Zerobyte job 13 ("Backups") ships it off-site to Backblaze every night at 02:00.
# Installed as /usr/local/sbin/proxmox-config-backup, triggered by proxmox-config-backup.timer.
# Why it exists and how to restore from it: docs/BACKUP.md §4.2 and §9.
#
# Reports to an Uptime Kuma push monitor when PUSH_URL is set (by the service, from
# /etc/default/proxmox-config-backup — the token stays out of this repository). The monitor
# alerts when no push arrives in time, which also covers a timer that never fires.

set -euo pipefail

# --- CONFIGURATION ---
PBS_CTID="103"
# rrsync on Pulsar maps "/" to /mnt/data/backups/proxmox-configs and refuses anything else
TARGET="astra-configs@192.168.1.201:/"
SSH_KEY="/root/.ssh/proxmox-config-backup_ed25519"
KNOWN_HOSTS="/root/.ssh/proxmox-config-backup_known_hosts"
HOST_FILES=(
    /etc/hostname
    /etc/hosts
    /etc/network/interfaces
    /etc/fstab
    /etc/systemd/system/mnt-pve-vault.mount
)
# Kuma displays the URL with "?status=up&msg=OK&ping=" appended: keep only the part before "?"
PUSH_URL="${PUSH_URL:-}"
PUSH_URL="${PUSH_URL%%\?*}"
# ---------------------

push() {
    [ -n "$PUSH_URL" ] || return 0
    curl -fsS -m 10 --retry 3 -o /dev/null -G "$PUSH_URL" \
        --data-urlencode "status=$1" --data-urlencode "msg=$2" \
        || echo "WARNING: could not reach Uptime Kuma" >&2
}

# Single exit point: every failure, `set -e` included, ends here and reports "down"
STAGING=""
finish() {
    local status=$?
    if [ -n "$STAGING" ]; then
        rm -rf "$STAGING"
    fi
    if [ "$status" -eq 0 ]; then
        push up "OK"
    else
        push down "Failed with exit code $status, see journalctl -u proxmox-config-backup on astra"
    fi
}
trap finish EXIT

# Staged in /run (tmpfs): the secrets are never written to Astra's disks a second time
STAGING=$(mktemp -d /run/proxmox-config-backup.XXXXXX)
mkdir "$STAGING"/{pve,pmxcfs,pbs,host}

# 1. /etc/pve as readable files. The dotfiles at its root (.members, .rrd, .vmlist...) are
#    runtime views generated by pmxcfs, not configuration.
rsync -rlt --exclude='/.*' --exclude='/priv/lock/' /etc/pve/ "$STAGING/pve/"

# 2. The pmxcfs database itself, the official recovery path (pve-docs, pmxcfs "Recovery").
#    .backup goes through SQLite's online backup API: consistent even while pmxcfs writes.
sqlite3 -readonly /var/lib/pve-cluster/config.db ".backup '$STAGING/pmxcfs/config.db'"
if [ "$(sqlite3 "$STAGING/pmxcfs/config.db" 'PRAGMA integrity_check;')" != "ok" ]; then
    echo "ERROR: the copy of config.db failed its integrity check, nothing sent." >&2
    exit 1
fi

# 3. The PBS configuration lives inside its LXC, not on the host. Lock files are skipped.
pct exec "$PBS_CTID" -- tar -C /etc --exclude='*.lck' --exclude='*.lock' -cf - proxmox-backup \
    | tar -C "$STAGING/pbs" --no-same-owner -xf -

# 4. Host files needed to rebuild Astra around the database: identity, network, vault mount
cp --parents "${HOST_FILES[@]}" "$STAGING/host/"

# 5. What produced this copy, to reinstall the same versions before restoring
{
    echo "Taken on $(hostname) at $(date --iso-8601=seconds)"
    echo
    echo "--- pveversion -v"
    pveversion -v
    echo
    echo "--- proxmox-backup-manager versions (LXC $PBS_CTID)"
    pct exec "$PBS_CTID" -- proxmox-backup-manager versions
} > "$STAGING/MANIFEST.txt"

# Every step above ran under `set -e`: if one failed, Pulsar still holds the last good copy.
rsync -rlpt --delete --chmod=D700,F600 \
    -e "ssh -i $SSH_KEY -o IdentitiesOnly=yes -o BatchMode=yes -o StrictHostKeyChecking=yes -o UserKnownHostsFile=$KNOWN_HOSTS" \
    "$STAGING/" "$TARGET"

echo "Proxmox configuration sent to $TARGET"
