apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-web-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: web
      port: {{ .Values.service.web.port }}
      targetPort: {{ .Values.service.web.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-sftp-svc
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: sftp
      port: {{ .Values.service.sftp.port }}
      targetPort: {{ .Values.service.sftp.targetPort }}
      nodePort: {{ .Values.service.sftp.nodePort }}
