apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: security
type: Opaque
stringData:
  # Generate the token with: openssl rand -base64 48
  ADMIN_TOKEN: "your_admin_token"
