apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: botenoal-es
  namespace: bots
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-store
    kind: ClusterSecretStore
  target:
    name: botenoal-secrets
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: BOTENOAL_TOKEN
    - secretKey: secret
      remoteRef:
        key: BOTENOAL_SECRET
    - secretKey: MongoDB
      remoteRef:
        key: BOTENOAL_MONGODB
    - secretKey: DashboardURL
      remoteRef:
        key: BOTENOAL_DASHBOARD_URL
