apiVersion: v1
kind: Secret
metadata:
  name: botenoal-secrets
  namespace: bots
type: Opaque
stringData:
  token: "your-discord-bot-token"
  secret: "your-discord-bot-secret"
  MongoDB: "your-mongodb-connection-string"
  DashboardURL: "https://botenoal.lan"
