apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: azerbot-es
  namespace: bots
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-store
    kind: ClusterSecretStore
  target:
    name: azerbot-secrets
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: AZERBOT_TOKEN
    - secretKey: secret
      remoteRef:
        key: AZERBOT_SECRET
    - secretKey: MongoDB
      remoteRef:
        key: AZERBOT_MONGODB
    - secretKey: DashboardURL
      remoteRef:
        key: AZERBOT_DASHBOARD_URL
