image:
  repository: ghcr.io/enoal-fauchille-bolle/azerbot
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80
  targetPort: 3000

ingress:
  hosts:
    - azerbot.lan

envFrom:
  - secretRef:
      name: azerbot-secrets

probes:
  liveness:
    path: /status
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    path: /status
    initialDelaySeconds: 5
    periodSeconds: 5

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

imagePullSecrets:
  - name: regcred-azerbot

externalSecrets:
  - name: azerbot-es
    targetName: azerbot-secrets
    data:
      - secretKey: token
        remoteRef:
          key: AZERBOT_TOKEN
      - secretKey: secret
        remoteRef:
          key: AZERBOT_SECRET
      - secretKey: MongoDB
        remoteRef:
          key: AZERBOT_MONGODB
      - secretKey: DashboardURL
        remoteRef:
          key: AZERBOT_DASHBOARD_URL
