image:
  repository: ghcr.io/enoal-fauchille-bolle/azerbot
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80
  targetPort: 3000

ingress:
  hosts:
    - azerbot.lan
  annotations:
    {}

probes:
  liveness:
    enabled: true
    path: /status
    initialDelaySeconds: 10
    periodSeconds: 10
  readiness:
    enabled: true
    path: /status
    initialDelaySeconds: 5
    periodSeconds: 5

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 256Mi

imagePullSecrets:
  - name: regcred-azerbot
