apiVersion: v1
kind: Service
metadata:
  name: criteri-fresque-backend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: criteri-fresque-backend
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app: criteri-fresque-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
