apiVersion: v1
kind: Service
metadata:
  name: criteri-fresque-frontend-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: criteri-fresque-frontend
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    app: criteri-fresque-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
