apiVersion: v1
kind: Secret
metadata:
  name: ntfy-secrets
  namespace: notifications
type: Opaque
stringData:
  # Format: "user:hash:role", users separated by a comma
  # Generate the password hash with: htpasswd -bnBC 10 "" YOUR_PASSWORD | tr -d ':\n'
  auth-users: "your_user:your_password_hash:admin"
