namespace: monitoring

image:
  repository: louislam/uptime-kuma
  tag: 2.3.2
  pullPolicy: IfNotPresent

replicaCount: 1

strategy:
  type: Recreate

service:
  port: 80
  targetPort: 3001

ingress:
  enabled: true
  hosts:
    - uptime.enoal.fr
    - status.enoal.fr

dns:
  policy: None
  nameservers:
    - 192.168.1.202
    - 10.43.0.10
  searches:
    - svc.cluster.local
    - cluster.local
    - lan

volumes:
  data:
    hostPath: /opt/k3s-data/uptimekuma
    mountPath: /app/data

resources:
  requests:
    cpu: 10m
    memory: 256Mi
  limits:
    cpu: 100m
    memory: 512Mi
