apiVersion: v1
kind: Service
metadata:
  name: infisical-app-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: infisical-app
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
