image:
  repository: ghcr.io/enoal-fauchille-bolle/redirector
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  hosts:
    - azerdev-discord.lan

env:
  - name: REDIRECT_URL
    value: "https://discord.gg/AfwMAQMwKj"

resources:
  requests:
    cpu: 10m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - name: regcred-azerdev-discord
