namespace: media

image:
  repository: docker.io/filebrowser/filebrowser
  tag: latest
  pullPolicy: Always

replicaCount: 1

strategy:
  type: Recreate

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  hosts:
    - filebrowser.enoal.fr

volumes:
  data:
    hostPath: /mnt/data/k3s-pvc/filebrowser
    mountPath: /srv
  db:
    hostPath: /opt/k3s-data/filebrowser
    mountPath: /database

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
