apiVersion: v1
kind: Secret
metadata:
  name: diun-secrets
  namespace: monitoring
type: Opaque
stringData:
  DIUN_NOTIF_DISCORD_WEBHOOKURL: "https://discord.com/api/webhooks/VOTRE_ID/VOTRE_TOKEN"
  # DIUN_NOTIF_NTFY_ENDPOINT: "https://ntfy.example.com"
  # DIUN_NOTIF_NTFY_TOPIC: "diun"
  # DIUN_NOTIF_NTFY_TOKEN: "your-token"
