services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v10.6.9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080
    restart: unless-stopped
