apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  diun.yml: |
    db:
      path: /data/diun.db

    watch:
      workers: 10
      schedule: "0 */6 * * *"
      jitter: 30s
      firstCheckNotif: false
      runOnStartup: true

    defaults:
      watchRepo: false
      notifyOn:
        - new
        - update
      sortTags: reverse

    notif:
      discord:
        webhookURL: ""
        renderEmbeds: true
        renderFields: true
        timeout: 10s

    providers:
      docker:
        endpoint: "unix:///var/run/docker.sock"
        watchByDefault: true
      kubernetes:
        watchByDefault: true
