apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: automation
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:2.29.11
          ports:
            - containerPort: 5678
          env:
            - name: N8N_HOST
              value: "n8n.enoal.fr"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
            - name: NODE_ENV
              value: "production"
            - name: WEBHOOK_URL
              value: "https://n8n.enoal.fr/"
            - name: GENERIC_TIMEZONE
              value: "Europe/Paris"
            - name: TZ
              value: "Europe/Paris"
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
          resources:
            requests:
              memory: "380Mi"
              cpu: "50m"
            limits:
              memory: "1Gi"
              cpu: "200m"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
            - name: local-files
              mountPath: /files
      volumes:
        - name: n8n-data
          hostPath:
            path: /opt/k3s-data/n8n/data
            type: Directory
        - name: local-files
          hostPath:
            path: /opt/k3s-data/n8n/files
            type: Directory
