services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.41
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Europe/Paris
      - BASE_URL=http://zerobyte.lan
      - APP_SECRET=${APP_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - ${RCLONE_CONFIG_PATH}:/root/.config/rclone:ro
      # Read-only mounts for various services
      - /opt/k3s-data/homer:/data/homer:ro # Homer
      - /opt/docker-data/portainer:/data/portainer:ro # Portainer
      - /opt/k3s-data/docker-registry:/data/docker-registry:ro # Docker Registry
      - /mnt/data/k3s-pvc/filebrowser:/data/filebrowser:ro # File Browser
      - /opt/k3s-data/criteri-fresque:/data/criteri-fresque:ro # Criteri Fresque
      - /opt/docker-data/crafty/config:/data/crafty/config:ro # Crafty Config
      - /mnt/data/docker-volumes/crafty/backups:/data/crafty/backups:ro # Crafty Backups
      - /opt/k3s-data/immich/library:/data/immich/library:ro # Immich Library
      - /mnt/data/backups:/data/backups:ro # Backups
      - /mnt/data/media/photos:/data/media/photos:ro # Photos
