services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.36.0
    container_name: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - "4096:4096"
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Europe/Paris
      - BASE_URL=http://zerobyte.lan
      - APP_SECRET=${APP_SECRET}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - ${RCLONE_CONFIG_PATH}:/root/.config/rclone:ro
