apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: azerbot
  namespace: bots
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: azerbot
  updatePolicy:
    updateMode: "Off"
