apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: couchdb
  namespace: productivity
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: couchdb
  updatePolicy:
    updateMode: "Off"
