apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: immich-postgres
  namespace: media
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: immich-postgres
  updatePolicy:
    updateMode: "Off"
