apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-runner-es
  namespace: github-runners
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-store
    kind: ClusterSecretStore
  target:
    name: github-runner-secret
    creationPolicy: Owner
  data:
    - secretKey: github_token
      remoteRef:
        key: GITHUB_RUNNERS_GITHUB_TOKEN
