apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/enoal-fauchille-bolle/astra-ops.git
    targetRevision: HEAD
    path: k3s/homer
  destination:
    server: https://kubernetes.default.svc
    namespace: dashboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
