apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa-system
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cowboysysop.github.io/charts/
    chart: vertical-pod-autoscaler
    targetRevision: "11.1.1"
    helm:
      values: |
        recommender:
          enabled: true
          extraArgs:
            pod-recommendation-min-cpu-millicores: "10"
            pod-recommendation-min-memory-mb: "10"
        updater:
          enabled: false
        admissionController:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
