apiVersion: v1
kind: Secret
metadata:
  name: sftpgo-secrets
  namespace: media
type: Opaque
stringData:
  host: smtp.resend.com
  port: "587"
  from: noreply@example.com
  encryption: "starttls"
  username: resend
  password: "<resend-api-key>"
