namespace: media

image:
  repository: ghcr.io/drakkan/sftpgo
  tag: v2.7.5
  pullPolicy: IfNotPresent

replicaCount: 1

strategy:
  type: Recreate

service:
  web:
    port: 8080
    targetPort: 8080
  sftp:
    port: 2022
    targetPort: 2022
    nodePort: 30022

ingress:
  enabled: true
  hosts:
    - sftpgo.lan

volumes:
  media:
    hostPath: /mnt/data/media
    mountPath: /data/media
  backups:
    hostPath: /mnt/data/backups
    mountPath: /data/backups
  filebrowser:
    hostPath: /mnt/data/k3s-pvc/filebrowser
    mountPath: /data/filebrowser
  data:
    hostPath: /opt/k3s-data/sftpgo
    mountPath: /var/lib/sftpgo

securityContext:
  runAsUser: 0

env:
  - name: SFTPGO_SMTP__HOST
    valueFrom:
      secretKeyRef:
        name: sftpgo-secrets
        key: host
  - name: SFTPGO_SMTP__PORT
    valueFrom:
      secretKeyRef:
        name: sftpgo-secrets
        key: port
  - name: SFTPGO_SMTP__FROM
    valueFrom:
      secretKeyRef:
        name: sftpgo-secrets
        key: from
  - name: SFTPGO_SMTP__USER
    valueFrom:
      secretKeyRef:
        name: sftpgo-secrets
        key: username
  - name: SFTPGO_SMTP__PASSWORD
    valueFrom:
      secretKeyRef:
        name: sftpgo-secrets
        key: password
  - name: SFTPGO_SMTP__ENCRYPTION
    valueFrom:
      secretKeyRef:
        name: sftpgo-secrets
        key: encryption

resources:
  requests:
    cpu: 10m
    memory: 80Mi
  limits:
    cpu: 200m
    memory: 192Mi

externalSecrets:
  - name: sftpgo-es
    targetName: sftpgo-secrets
    data:
      - secretKey: host
        remoteRef:
          key: SMTP_HOST
      - secretKey: port
        remoteRef:
          key: SMTP_PORT
      - secretKey: from
        remoteRef:
          key: SFTPGO_SMTP_FROM
      - secretKey: encryption
        remoteRef:
          key: SFTPGO_SMTP_ENCRYPTION
      - secretKey: username
        remoteRef:
          key: SMTP_USERNAME
      - secretKey: password
        remoteRef:
          key: SFTPGO_SMTP_PASSWORD
