{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster-store
    kind: ClusterSecretStore
  target:
    name: {{ .targetName }}
    creationPolicy: Owner
    {{- if .targetTemplate }}
    template:
      {{- toYaml .targetTemplate | nindent 6 }}
    {{- end }}
  data:
    {{- toYaml .data | nindent 4 }}
---
{{- end }}
