apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secrets
  namespace: devops
type: Opaque
stringData:
  # Generate the htpasswd with: htpasswd -Bbn user password
  htpasswd: 'user:hashedpassword'
